### ISSUE TITLE
Hey Please help I cant find xbee.py file on my /WEB/python directory. How can I fix this?

### ISSUE THREAD

**Issue by yunusemreemik** [digidotcom/xbgw-app#2]
My xbee industrial gateway give this error every reboot;
Traceback (most recent call last):
Oct 22 11:57:41 local7.info pylog: File "xbgw_main.py", line 13, in
Oct 22 11:57:41 local7.info pylog: from xbgw.xbee.manager import XBeeEventManager
Oct 22 11:57:41 local7.info pylog: File "/home/builder/bamboo-agent-home/xml-data/build-dir/XBGW-MASTER4-JOB1/xbgw/xbee/manager.py", line 1, in
Oct 22 11:57:41 local7.info pylog: File "/userfs/WEB/python/xbee.py", line 20, in
Oct 22 11:57:41 local7.info pylog: AttributeError: 'module' object has no attribute 'AF_ZIGBEE'

**Comment by mikewadsten** [comment]
I think the error is because you have an `xbee.py` file in your `/userfs/WEB/python` directory, as evidenced here:

```
Oct 22 11:57:41 local7.info pylog: File "/userfs/WEB/python/xbee.py", line 20, in
```

On XBee Industrial Gateway, `import xbee` normally will import the `xbee` module built into the gateway. However, if another `xbee.py` module is found earlier in `sys.path` (of which the current working directory, `/userfs/WEB/python`, is effectively the first entry by default), then _that_ will be imported, and not the built-in module. This is just how Python (2.7 and earlier) works.

Try renaming your xbee.py file to something else, such as `my_xbee.py`. (You will need to change `import xbee` to `import my_xbee` in any code you wrote that wants to use _that_ "xbee.py" file. But don't change any `import xbee` in the code already in this repository.)

---

To further clarify the issue, I'll use another module that's built into Python 2.7 - `ftplib.py`. If I `cd` into an empty directory, and create an empty `ftplib.py` file, this code will error out:

```python
import ftplib
ftplib.FTP()  # AttributeError: 'module' object has no attribute 'FTP'
```

This happens because the `ftplib.py` file in the current directory is imported _instead of_ the `ftplib.py` provided by the Python standard library. The same thing is happening here.

**Comment by yunusemreemik** [comment]
I searched each folder but there is no xbee.py in any directory. I can share THE xbgw_main.py file with you. Maybe its gonna help

**Comment by mikewadsten** [comment]
Check whether there is a `/userfs/WEB/python/xbee.pyc` file. (Python automatically byte-compiles source code files and saves them as `.pyc`.) If this file does not exist, then please SSH into the gateway and run this command and reply with the response:

```
ls -la /userfs/WEB/python
```
